checkpointing_steps: null
gradient_accumulation_steps: 1
hidden_dropout: 0.1
hub_model_id: null
hub_token: null
ignore_mismatched_sizes: false
learning_rate: 5.0e-05
lr_scheduler_type: linear
max_length: 128
max_train_steps: 390
model_name_or_path: bert-base-cased
num_train_epochs: 5
num_warmup_steps: 0
output_dir: /content/drive/MyDrive/Masterarbeit/fantastic-umbrella/runs/run-20230614_153755
pad_to_max_length: false
per_device_eval_batch_size: 8
per_device_train_batch_size: 32
push_to_hub: false
report_to: tensorboard
resume_from_checkpoint: null
seed: 0
task_name: rte
train_data_frac: 1.0
train_file: null
use_modded: false
use_pretrain_dropout_in_first_pass: true
use_slow_tokenizer: false
validation_file: null
weight_decay: 0.0
with_tracking: true
